### ISSUE TITLE
Call DeviceDetector::parser() whenever it's required

### ISSUE THREAD

**Issue by renedelima** [acsiomatic/device-detector-bundle#7]
Make DeviceDetector::parser() be called automatically whenever someone asks for DeviceDetector parsed data.

### Current semantic

```php
class SomeService
{
    public function doSomething(DeviceDetector $device)
    {
        $device->parse();
        $device->isSmartphone();
    }
}
```

### Proposed semantic

```php
class SomeService
{
    public function doSomething(DeviceDetector $device)
    {
        $device->isSmartphone(); // implicit call $device->parse()
    }
}
```

**Comment by renanbr** [comment]
We could try proxy approach:

- [ocramius/proxy-manager](https://packagist.org/packages/ocramius/proxy-manager)
- [friendsofphp/proxy-manager-lts](https://packagist.org/packages/friendsofphp/proxy-manager-lts) for wider support
